[package]
name = "rsmatrix"
version = "0.1.0"
authors = ["Dominik Nakamura <dnaka91@gmail.com>"]
edition = "2018"

[dependencies]
anyhow = "1.0.34"
clap = "3.0.0-beta.2"
rand = "0.7.3"
termion = "1.5.5"
tui = "0.13.0"

[dependencies.attohttpc]
version = "0.16.0"
optional = true
default-features = false
features = ["json", "tls-rustls"]

[dependencies.serde]
version = "1.0.117"
optional = true
features = ["derive"]

[features]
default = ["twitch"]
twitch = ["attohttpc", "serde"]

[profile.release]
lto = true
panic = "abort"
