[package]
name = "rsmatrix"
version = "0.1.2"
authors = ["Dominik Nakamura <dnaka91@gmail.com>"]
edition = "2021"
license = "GPL-3.0-only"

[dependencies]
anyhow = "1.0.70"
clap = { version = "4.2.2", features = ["derive"] }
crossterm = "0.26.1"
rand = "0.8.5"
ratatui = "0.20.1"

[dependencies.attohttpc]
version = "0.25.0"
optional = true
default-features = false
features = ["json", "tls-rustls"]

[dependencies.serde]
version = "1.0.160"
optional = true
features = ["derive"]

[features]
default = ["twitch"]
twitch = ["attohttpc", "serde"]

[profile.release]
lto = true
