[package]
name = "rsmatrix"
version = "0.1.0"
authors = ["Dominik Nakamura <dnaka91@gmail.com>"]
edition = "2018"

[dependencies]
anyhow = "1.0.53"
clap = { version = "3.0.10", features = ["derive"] }
rand = "0.8.4"
termion = "1.5.6"
tui = { version = "0.17.0", default-features = false, features = ["termion"] }

[dependencies.attohttpc]
version = "0.18.0"
optional = true
default-features = false
features = ["json", "tls-rustls"]

[dependencies.serde]
version = "1.0.135"
optional = true
features = ["derive"]

[features]
default = ["twitch"]
twitch = ["attohttpc", "serde"]

[profile.release]
lto = true
