[package]
name = "rsmatrix"
version = "0.1.0"
authors = ["Dominik Nakamura <dnaka91@gmail.com>"]
edition = "2021"
license = "GPL-3.0-only"

[dependencies]
anyhow = "1.0.57"
clap = { version = "3.2.4", features = ["derive"] }
crossterm = "0.23.2"
rand = "0.8.5"
tui = "0.18.0"

[dependencies.attohttpc]
version = "0.19.1"
optional = true
default-features = false
features = ["json", "tls-rustls"]

[dependencies.serde]
version = "1.0.137"
optional = true
features = ["derive"]

[features]
default = ["twitch"]
twitch = ["attohttpc", "serde"]

[profile.release]
lto = true
