[package]
name = "rsmatrix"
version = "0.1.1"
authors = ["Dominik Nakamura <dnaka91@gmail.com>"]
edition = "2021"
license = "GPL-3.0-only"

[dependencies]
anyhow = "1.0.65"
clap = { version = "4.0.10", features = ["derive"] }
crossterm = "0.25.0"
rand = "0.8.5"
tui = "0.19.0"

[dependencies.attohttpc]
version = "0.22.0"
optional = true
default-features = false
features = ["json", "tls-rustls"]

[dependencies.serde]
version = "1.0.145"
optional = true
features = ["derive"]

[features]
default = ["twitch"]
twitch = ["attohttpc", "serde"]

[profile.release]
lto = true
